#!/bin/sh

# Copyright 2025 @VKrishna04
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd "$(dirname "$0")/.."

# Detect the operating system and run the corresponding script
if [ "$(uname)" = "Linux" ]; then
    echo "Detected Linux OS"
    ./scripts/run_app.sh
elif [ "$(uname)" = "Darwin" ]; then
    echo "Detected macOS"
    ./scripts/run_app.sh
elif [ "$(uname -o)" = "Msys" ]; then
    echo "Detected Windows OS"
    ./scripts/run_app.bat
else
    echo "Unsupported OS"
    exit 1
fi